"""数据库连接层（PostgreSQL / Supabase）"""

from .connection import (
    build_conninfo,
    db_connection,
    get_pool,
    health_check,
    is_database_configured,
    reset_pool,
)
from .repository import (
    ExtractionResultRow,
    SaveExtractionOutcome,
    TaskListPage,
    TaskRow,
    get_latest_extraction_by_task_id,
    get_latest_extraction_by_task_uuid,
    get_task_by_task_id,
    get_task_by_task_id_in_conn,
    get_task_by_uuid,
    get_task_timeline,
    insert_agent_log,
    insert_audit_log,
    insert_audit_log_conn,
    insert_document_asset,
    insert_fill_report,
    insert_task_step,
    list_tasks,
    resolve_task_id,
    save_extraction_from_agent_payload,
    save_extraction_from_agent_payload_safe,
    set_task_review,
)
from .workflow_persistence import persist_workflow_execute_begin, persist_workflow_execute_end

__all__ = [
    "ExtractionResultRow",
    "SaveExtractionOutcome",
    "TaskListPage",
    "TaskRow",
    "build_conninfo",
    "db_connection",
    "get_latest_extraction_by_task_id",
    "get_latest_extraction_by_task_uuid",
    "get_pool",
    "get_task_by_task_id",
    "get_task_by_task_id_in_conn",
    "get_task_by_uuid",
    "get_task_timeline",
    "health_check",
    "insert_agent_log",
    "insert_audit_log",
    "insert_audit_log_conn",
    "insert_document_asset",
    "insert_fill_report",
    "insert_task_step",
    "is_database_configured",
    "list_tasks",
    "persist_workflow_execute_begin",
    "persist_workflow_execute_end",
    "reset_pool",
    "resolve_task_id",
    "save_extraction_from_agent_payload",
    "save_extraction_from_agent_payload_safe",
    "set_task_review",
]
